# Generated by Django 4.1.7 on 2023-11-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationsdocuments',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.documents', verbose_name='ID документа'),
        ),
        migrations.AlterField(
            model_name='relationsdocuments',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.files', verbose_name='ID файла'),
        ),
        migrations.AlterField(
            model_name='relationsfiles',
            name='id_entities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.entities', verbose_name='ID категории'),
        ),
        migrations.AlterField(
            model_name='relationsfiles',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.files', verbose_name='ID файла'),
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.documents', verbose_name='ID документа'),
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='id_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.entities', verbose_name='ID сущности'),
        ),
        migrations.AlterField(
            model_name='tag_relation',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.tags', verbose_name='ID тэга'),
        ),
    ]
